# Generated by Django 4.2.6 on 2023-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_children_caretaker_id_alter_children_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.IntegerField(null=True)),
                ('date_app', models.DateTimeField()),
            ],
        ),
    ]
