# Generated by Django 4.2.6 on 2023-10-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('caretaker_id', models.IntegerField()),
                ('blood_group', models.CharField(max_length=30)),
                ('medical_condition', models.TextField(max_length=300)),
            ],
        ),
    ]
