# Generated by Django 4.2.6 on 2023-10-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_address_alter_user_caretaker_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('msg', models.TextField(max_length=500)),
            ],
        ),
    ]
