# Generated by Django 4.2.6 on 2023-10-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='caretaker_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
