# Generated by Django 4.2.6 on 2023-10-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_user_occupation_alter_user_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='caretaker_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
